# nginx proxy address - http://172.17.0.1:60236

name: budgetboard
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  client:
    image: ghcr.io/teelur/budget-board/client:release
    container_name: budgetboard-client
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      PORT: 80
      VITE_API_URL: budgetboard-server
    ports:
      - '172.17.0.1:60236:80'
    depends_on:
      - db
      - server
    networks:
      - budgetboard

  server:
    image: ghcr.io/teelur/budget-board/server:release
    container_name: budgetboard-server
    hostname: budgetboard-server
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      AUTO_UPDATE_DB: true
      CLIENT_URL: budgetboard-client
      POSTGRES_USER: ${DB_ADMIN_USER:-postgres}
      POSTGRES_HOST: budgetboard-db
      POSTGRES_DATABASE: ${DB_CREATE_DATABASE_NAME:-budgetboard}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASS:-changeme_admin_password}
      Logging__LogLevel__Default: Information
    depends_on:
      db:
        condition: service_healthy
    networks:
      - budgetboard

  db:
    image: postgres:latest
    container_name: budgetboard-db
    hostname: budgetboard-db
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-budgetboard}
      POSTGRES_USER: ${DB_ADMIN_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASS:-changeme_admin_password}
    volumes:
      - './volumes/data/db/postgres/budgetboard:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - budgetboard

networks:
  budgetboard:
    name: budgetboard
    external: false
